#62 New pre-req update
jpgough/api-workshop pull request #63
Opened 2020-02-09 22:08 UTC by Budlee

2020-02-11 15:52 UTC, jpgough commented on prerequisites/README.md
> +### Swagger diff
This should be removed

2020-02-11 15:52 UTC, jpgough requested changes
One small change to remove swagger

2020-02-11 16:05 UTC, Budlee commented on prerequisites/README.md
> +### Swagger diff
Done

2020-02-16 00:03 UTC, jpgough approved these changes

2020-02-16 00:03 UTC, merged